spring:
  datasource:
    url: "jdbc:postgresql://mcedu.co.kr:5432/lol_dev"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: bitbot12#$
  jwt:
    secret: local_yache
  thymeleaf:
    cache: false
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  devtools:
    livereload:
      enabled: true
  web:
    resources:
      cache:
        cachecontrol:
          no-store: true
  mvc:
    static-path-pattern: /static/**
logging:
  config: classpath:logback-local.xml

security:
  ignore-url: /static/**, /api/test/*, /favicon.ico, /user/checkId/*, /user/checkEmail/*,  /v2/api-docs, /configuration/**, /swagger*/**, /webjars/**

management:
  endpoints:
    web:
      exposure:
        include: metrics,heath,prometheus
    jmx:
      exposure:
        include: "*"
  server:
    port: 8082
  endpoint:
    metrics:
      enabled: true