spring:
  datasource:
    url: "jdbc:postgresql://mcedu.co.kr:5432/lol_dev"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: bitbot12#$

logging:
  file:
    path: classpath:/logback-local.xml