spring:
  profiles:
    active: local

---
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/lol"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: bitbot12#$
  jwt:
    secret: prod_yache
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

logging:
  file:
    path: classpath:/logback-local.xml

security:
  ignore-url: /static/**, /login, /api/test/*, /favicon.ico