spring:
  profiles:
    active: local

---
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/lol"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: bitbot12#$
    hikari:
      minimum-idle: 2
  jwt:
    secret: prod_yache
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  web:
    resources:
      cache:
        cachecontrol:
          no-store: true
  mvc:
    static-path-pattern: /static/**

logging:
  config: classpath:logback-prod.xml

security:
  ignore-url: /static/**, /api/test/*, /favicon.ico, /user/checkId/*, /user/checkEmail/*
server:
  port: 8081

springfox:
  documentation:
    enabled: false
    auto-startup: false

management:
  endpoints:
    web:
      exposure:
        include: metrics,heath,prometheus
    jmx:
      exposure:
        include: "*"
  server:
    port: 8082
  endpoint:
    metrics:
      enabled: true

lol:
  cdn-url: https://ddragon.leagueoflegends.com/cdn